name: flutter_cl
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.3.0
  get_it: ^8.0.2
  watch_it: ^1.5.1
  gap: ^3.0.1
  lucid_validation: ^1.1.0
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  http: ^1.2.2
  timeago: ^3.7.0
  get: ^4.6.6
  dio: ^5.7.0
  signals: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  mockito: ^5.4.4
  build_runner: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/json/
